services:
  db:
    image: postgres:latest
    ports:
      - "5434:5434"
    env_file:
      - .env
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
